import { useEffect, useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";

type Campaign={id:string;name:string;description:string|null;enabled:boolean;window_size:number;qualification_message:string};
type Prize={id:string;campaign_id:string;name:string;description:string|null;image_url:string;emoji:string;prize_type:string;value:number;allocation_count:number;allocation_window:number;qualification_label:string;fulfilment_type:string;fulfilment_config:Record<string,unknown>;enabled:boolean;sort_order:number};
type Stage={id:string;campaign_id:string;stage_number:number;title:string;instructions:string|null;stage_type:string;sponsor_name:string|null;action_url:string|null;form_config:Record<string,unknown>;ad_enabled:boolean;released_at:string|null;notification_title:string|null;notification_body:string|null};

const blankPrize=():Partial<Prize>=>({name:"",description:"",image_url:"",emoji:"🎁",prize_type:"physical",value:0,allocation_count:1,allocation_window:10000,qualification_label:"You have qualified for this prize.",fulfilment_type:"claim_form",fulfilment_config:{},enabled:true,sort_order:0});
const blankStage=():Partial<Stage>=>({stage_number:1,title:"General Claim Form",instructions:"Complete this step to remain in the qualification pool.",stage_type:"form",sponsor_name:"",action_url:"",form_config:{fields:[{key:"contact_method",label:"How would you like to receive this prize?",type:"text",required:true}]},ad_enabled:true,released_at:null,notification_title:"Qualification challenge is ready",notification_body:"Continue your prize qualification challenge."});

export function AdminRewardEngine(){
 const [campaign,setCampaign]=useState<Campaign|null>(null); const [prizes,setPrizes]=useState<Prize[]>([]); const [stages,setStages]=useState<Stage[]>([]);
 const [editing,setEditing]=useState<Partial<Prize>|null>(null); const [stage,setStage]=useState<Partial<Stage>|null>(null); const [saving,setSaving]=useState(false); const [qualifications,setQualifications]=useState<Array<{qualification_id:string;user_id:string;display_name:string;prize_name:string;status:string;current_stage:number;created_at:string}>>([]);
 const load=async()=>{const {data:c}=await supabase.from("cp_reward_campaigns").select("*").order("created_at").limit(1).maybeSingle(); if(!c)return; setCampaign(c as Campaign); const [{data:p},{data:s}]=await Promise.all([supabase.from("cp_reward_prizes").select("*").eq("campaign_id",c.id).order("sort_order"),supabase.from("cp_reward_stages").select("*").eq("campaign_id",c.id).order("stage_number")]); setPrizes((p??[]) as Prize[]); setStages((s??[]) as Stage[]); const {data:q}=await supabase.rpc("cp_admin_list_reward_qualifications",{p_campaign_id:c.id}); setQualifications((q??[]) as typeof qualifications);};
 useEffect(()=>{void load()},[]);
 const saveCampaign=async()=>{if(!campaign)return;setSaving(true);await supabase.rpc("cp_admin_reward_campaign_upsert",{p_id:campaign.id,p_name:campaign.name,p_description:campaign.description,p_enabled:campaign.enabled,p_window_size:campaign.window_size,p_qualification_message:campaign.qualification_message});setSaving(false);await load();};
 const savePrize=async()=>{if(!campaign||!editing)return;setSaving(true);await supabase.rpc("cp_admin_reward_prize_upsert",{p_id:editing.id??null,p_campaign_id:campaign.id,p_name:editing.name??"",p_description:editing.description??"",p_image_url:editing.image_url??"",p_emoji:editing.emoji??"🎁",p_prize_type:editing.prize_type??"physical",p_value:Number(editing.value??0),p_allocation_count:Number(editing.allocation_count??0),p_allocation_window:Number(editing.allocation_window??campaign.window_size),p_qualification_label:editing.qualification_label??"You have qualified for this prize.",p_fulfilment_type:editing.fulfilment_type??"claim_form",p_fulfilment_config:editing.fulfilment_config??{},p_enabled:editing.enabled!==false,p_sort_order:Number(editing.sort_order??0)});setSaving(false);setEditing(null);await load();};
 const saveStage=async()=>{if(!campaign||!stage)return;setSaving(true);await supabase.rpc("cp_admin_reward_stage_upsert",{p_id:stage.id??null,p_campaign_id:campaign.id,p_stage_number:Number(stage.stage_number??1),p_title:stage.title??"",p_instructions:stage.instructions??"",p_stage_type:stage.stage_type??"form",p_enabled:true,p_sponsor_name:stage.sponsor_name??"",p_action_url:stage.action_url??"",p_form_config:stage.form_config??{},p_ad_enabled:stage.ad_enabled!==false,p_released_at:stage.released_at??null,p_notification_title:stage.notification_title??"Qualification challenge is ready",p_notification_body:stage.notification_body??"Continue your prize qualification challenge."});setSaving(false);setStage(null);await load();};
 return <div className="space-y-6">
  <div><h2 className="font-display text-xl font-bold">Reward Engine</h2><p className="text-xs text-muted-foreground">Control exact qualification allocations, prize fulfilment and multi-stage screening.</p></div>
  {campaign?<section className="space-y-3 rounded-2xl border bg-card p-4">
   <div className="grid gap-3 sm:grid-cols-2"><Input value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})} placeholder="Campaign name"/><Input type="number" value={campaign.window_size} onChange={e=>setCampaign({...campaign,window_size:Number(e.target.value)})} placeholder="Spins per window"/></div>
   <Textarea value={campaign.qualification_message} onChange={e=>setCampaign({...campaign,qualification_message:e.target.value})} placeholder="Qualification message"/>
   <div className="flex items-center justify-between"><span className="text-sm">Wheel enabled</span><Switch checked={campaign.enabled} onCheckedChange={v=>setCampaign({...campaign,enabled:v})}/><Button onClick={saveCampaign} disabled={saving}><Save className="mr-2 size-4"/>Save</Button></div>
  </section>:null}
  <section className="space-y-3 rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Prizes & allocation slots</h3><Button size="sm" onClick={()=>setEditing(blankPrize())}><Plus className="mr-1 size-4"/>Prize</Button></div>
   <div className="space-y-2">{prizes.map(p=><div key={p.id} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><div className="font-semibold">{p.emoji} {p.name}</div><div className="text-xs text-muted-foreground">{p.allocation_count} qualifier(s) / {p.allocation_window.toLocaleString()} spins · {p.fulfilment_type}</div></div><Button size="sm" variant="outline" onClick={()=>setEditing(p)}>Edit</Button><Button size="icon" variant="ghost" onClick={async()=>{await supabase.rpc("cp_admin_reward_prize_delete",{p_id:p.id});await load()}}><Trash2 className="size-4"/></Button></div>)}</div>
  </section>
<section className="space-y-3 rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Qualification & finalist pool</h3><Button size="sm" variant="outline" onClick={()=>void load()}>Refresh</Button></div><div className="space-y-2">{qualifications.length===0?<p className="text-xs text-muted-foreground">No qualifiers yet.</p>:qualifications.slice(0,100).map(q=><div key={q.qualification_id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><div className="truncate font-semibold">{q.display_name} · {q.prize_name}</div><div className="text-xs text-muted-foreground">Stage {q.current_stage} · {q.status}</div></div>{q.status!=="winner"&&q.status!=="eliminated"?<Button size="sm" onClick={async()=>{await supabase.rpc("cp_admin_select_reward_winner",{p_qualification_id:q.qualification_id});await load()}}>Select final winner</Button>:null}</div>)}</div><p className="text-[11px] text-muted-foreground">The admin can progressively screen qualifiers, then select the final winner from the remaining pool.</p></section>
  <section className="space-y-3 rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Qualification stages</h3><Button size="sm" onClick={()=>setStage({...blankStage(),stage_number:stages.length+1})}><Plus className="mr-1 size-4"/>Stage</Button></div>
   {stages.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl border p-3"><div><b>Stage {s.stage_number}: {s.title}</b><div className="text-xs text-muted-foreground">{s.stage_type}{s.sponsor_name?" · "+s.sponsor_name:""}</div></div><Button size="sm" variant="outline" onClick={()=>setStage(s)}>Edit</Button></div>)}
  </section>
  {editing?<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border bg-card p-4 space-y-3"><h3 className="font-bold">{editing.id?"Edit":"Add"} prize</h3><Input value={editing.name??""} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Prize name"/><Input value={editing.image_url??""} onChange={e=>setEditing({...editing,image_url:e.target.value})} placeholder="Prize image URL"/><Input value={editing.emoji??""} onChange={e=>setEditing({...editing,emoji:e.target.value})} placeholder="Emoji"/><Input value={editing.prize_type??""} onChange={e=>setEditing({...editing,prize_type:e.target.value})} placeholder="bc / vip / data / physical / lead / try_again"/><Input type="number" value={editing.value??0} onChange={e=>setEditing({...editing,value:Number(e.target.value)})} placeholder="Value"/><Input type="number" value={editing.allocation_count??0} onChange={e=>setEditing({...editing,allocation_count:Number(e.target.value)})} placeholder="Qualifiers in window"/><Input type="number" value={editing.allocation_window??campaign?.window_size??10000} onChange={e=>setEditing({...editing,allocation_window:Number(e.target.value)})} placeholder="Window size"/><Input value={editing.fulfilment_type??""} onChange={e=>setEditing({...editing,fulfilment_type:e.target.value})} placeholder="automatic_bc / automatic_vip / claim_form / trivia / lead_form / browser / manual"/><Input value={editing.qualification_label??""} onChange={e=>setEditing({...editing,qualification_label:e.target.value})} placeholder="Qualification message"/><div className="flex gap-2"><Button onClick={savePrize} disabled={saving}>Save</Button><Button variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button></div></div></div>:null}
  {stage?<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border bg-card p-4 space-y-3"><h3 className="font-bold">Qualification stage</h3><Input type="number" value={stage.stage_number??1} onChange={e=>setStage({...stage,stage_number:Number(e.target.value)})} placeholder="Stage number"/><Input value={stage.title??""} onChange={e=>setStage({...stage,title:e.target.value})} placeholder="Title"/><Textarea value={stage.instructions??""} onChange={e=>setStage({...stage,instructions:e.target.value})} placeholder="Instructions"/><Input value={stage.notification_title??""} onChange={e=>setStage({...stage,notification_title:e.target.value})} placeholder="Notification title"/><Textarea value={stage.notification_body??""} onChange={e=>setStage({...stage,notification_body:e.target.value})} placeholder="Notification message"/><Input value={stage.stage_type??""} onChange={e=>setStage({...stage,stage_type:e.target.value})} placeholder="form / lead / trivia / browser / engagement / manual"/><Input value={stage.sponsor_name??""} onChange={e=>setStage({...stage,sponsor_name:e.target.value})} placeholder="Sponsor name"/><Input value={stage.action_url??""} onChange={e=>setStage({...stage,action_url:e.target.value})} placeholder="Sponsor/browser URL"/><Textarea value={JSON.stringify(stage.form_config??{},null,2)} onChange={e=>{try{setStage({...stage,form_config:JSON.parse(e.target.value)})}catch{}}} placeholder='{"fields":[{"key":"email","label":"Email","required":true}]}'/><div className="flex gap-2"><Button onClick={saveStage} disabled={saving}>Save</Button><Button variant="ghost" onClick={()=>setStage(null)}>Cancel</Button></div></div></div>:null}
 </div>;
}